swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
        - Transactions
      summary: Get all accounts for current user
      description: Retrieve accounts for a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '400':
          description: The request could not be processed due to missing or invalid parameters. Please ensure the request contains valid information.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      tags:
        - Transactions
      summary: Get a specific account for current user
      description: Retrieve a specific account for a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: The request could not be processed due to missing or invalid parameters. Please ensure the request contains valid information.
        '500':
          description: Internal Server Error
  /user/account/{accountId}/transactions:
    get:
      tags:
        - Transactions
      summary: Get user transactions by account id
      description: Retrieve transactions for a user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: The request could not be processed due to missing or invalid parameters. Please ensure the provided account ID is correct and the request contains valid information.
        '500':
          description: Internal Server Error
  /user/account/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get a specific transaction
      description: Retrieve a specific transaction by its ID and account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: The request could not be processed due to invalid parameters or missing information in the request. Please ensure the provided transaction ID is correct.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}/category:
    patch:
      tags:
        - Transactions
      summary: Update an existing transaction (category)
      description: Updating a transaction's category by its ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionsId
          description: Transaction's ID
          required: true
          type: integer
        - in: body
          name: body
          required: true
          description: Update transaction's informations
          schema:
              $ref: '#/definitions/TransactionsUpdateCategory'
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: The request could not be processed due to missing or invalid parameters. Please ensure the provided account ID and transaction ID are correct, and the request body contains valid information.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}/notes:
    patch:
      tags:
        - Transactions
      summary: Update an existing transaction (notes)
      description: Updating transaction's notes by its ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionsId
          description: Transaction's ID
          required: true
          type: integer
        - in: body
          name: body
          required: true
          description: Update transaction's informations
          schema:
              $ref: '#/definitions/TransactionsUpdateNotes'
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: The request could not be processed due to missing or invalid parameters. Please ensure the provided account ID and transaction ID are correct, and the request body contains valid information.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      amount:
        type: number
      accountId:
        type: integer
      date:
        type: string
        format: date
        description: Transaction date
  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      ammount:
        type: number
  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsUpdateNotes:
    type: object
    properties:
      notes:
        type: string